### ISSUE TITLE
AD domain controller not initialized for single-word domains.

### ISSUE THREAD

**Issue by luisartolag** [teradici/cloud_deployment_scripts#107]
If the AD domain is a single word, e.g. `demo`, the deployment would apparently succeed, but the AD domain controller would fail to initialize properly. As a result, machines are unable to join the domain. The error does not percolate up to the Terraform process. It would be very helpful if it did somehow to stop the deployment. Upstream client tools and users should perform validation and make sure that the domain complies with the AD policies for being at least two tokens separated by dots, e.g. `studio.demo` However, it should fail if any errors occur during configuration of AD controller. See GoogleCloudPlatform/solutions-cloud-orchestrate#2 for reference.

**Comment by shermanyin** [comment]
Will consider using this feature to valiate input: https://www.terraform.io/docs/configuration/variables.html#custom-validation-rules

**Comment by shermanyin** [comment]
regex has been introduced to make sure domain is not a single word. Closing as fixed.
