### ISSUE TITLE
Anything special to do for ssh?

### ISSUE THREAD

**Issue by infintropy** [teradici/cloud_deployment_scripts#145]
I'm unable to get in via ssh after creating workstations. (Specifically trying centos gfx after doing a single-connector deployment). I understand to ssh I need to connect to CAC as bastion, but when I do I'm consistently rejected. 

made key with `ssh-keygen -t rsa` @ `~/.ssh/id_rsa`

var in terraform: `~/.ssh/id_rsa.pub`

attempting connection with CAC via `ssh -i -A -v ~/.ssh/id_rsa cam_admin@54.219.124.29`

No dice. Any thoughts? I need to get these workstations wrapped into ansible and I'm currently unable to. Thank you for any thoughts or assistance.

**Comment by Edwin-Pau** [comment]
Hello! Thanks for reaching out. Are you using the AWS or GCP single-connector deployment?

**Comment by infintropy** [comment]
Very sorry, the AWS one.

**Comment by Edwin-Pau** [comment]
Please try using the user ```ubuntu``` for the AWS deployments on the CAC. For more information on the different login users for each VM, please refer to our [Troubleshooting](https://github.com/teradici/cloud_deployment_scripts/blob/master/docs/troubleshooting.md) page.

**Comment by infintropy** [comment]
Im tremendously sorry for overlooking that table. Thank you for the prompt help!  Excellent build quality by the way!

Cheers
