### ISSUE TITLE
GCP Quickstart Deployment --- Issue with Google Cloud Shell 

### ISSUE THREAD

**Issue by nathania4c** [teradici/cloud_deployment_scripts#184]
**Description**
Ran into this problem when executing the python script
`./gcp-cloudshell-quickstart.py` 

<img width="1440" alt="edited" src="https://user-images.githubusercontent.com/58287848/104524019-a7f09180-55b3-11eb-8c77-aa6fae9d3892.png">

_*You might also see an error message about needing the "compute.project.get" permission_

**What may have fixed the problem:**
- Added the permissions by running the command: `gcloud projects add-iam-policy-binding [PROJECT_ID] --member=serviceAccount:[PROJECT_NUMBER]-compute@developer.gserviceaccount.com --role=roles/compute.admin`
     - solution found here: [https://stackoverflow.com/questions/58768924/cloud-container-clusters-create-compute-networks-get-permission-error](https://stackoverflow.com/questions/58768924/cloud-container-clusters-create-compute-networks-get-permission-error)
- Toggling by enabling and then disabling the Kubernetes Engine API (the GKE should be disabled) might have somehow corrected the permissions

**Possible Environment**

<img width="737" alt="Screen Shot 2021-01-13 at 3 13 16 PM" src="https://user-images.githubusercontent.com/58287848/104522419-387aa200-55b3-11eb-8d97-469dc2d77adf.png">

- When running a gcloud command for the first time in a new shell, an "Authorise Cloud Shell" prompt should show up, but when this issue happened, it did not. Note the "!Untrusted" sign, which expands to the following prompt
     -  Note: the shell might suggest running the command `gcloud auth login` , but this might not solve this problem because it will only authorize user accounts, not service accounts. 
     - See: [https://cloud.google.com/sdk/docs/authorizing](https://cloud.google.com/sdk/docs/authorizing)
- Perhaps when the cloud shell was created, some permissions were somehow missing 
     - "Untrusted" means the default cloudshell image was not launched, so the credentials needed aren't there
     - See [https://offensi.com/2019/12/16/4-google-cloud-shell-bugs-explained-bug-2/](https://offensi.com/2019/12/16/4-google-cloud-shell-bugs-explained-bug-2/) 
     - Google Cloud Shell provisions a GCE VM instance
     -  The missing permissions was GCE permissions
- See [https://cloud.google.com/shell/docs/how-cloud-shell-works](https://cloud.google.com/shell/docs/how-cloud-shell-works)

**Reproducing the Issue** 
_may not work every time trouble reproducing the issue_
- Created a new GCP project and resetting the cloud shell --- worked in reproducing the error once
     - [https://cloud.google.com/shell/docs/resetting-cloud-shell](https://cloud.google.com/shell/docs/resetting-cloud-shell)   
- Changing the region and zone --- does not reproduce
- Further toggling with the GKE API --- does not reproduce
- Trying it on another VM

**Interesting Notes**
- You can use GKE features with GCE permissions: [https://cloud.google.com/kubernetes-engine/docs/how-to/iam](https://cloud.google.com/kubernetes-engine/docs/how-to/iam)
- When grabbing the metadata, the user account did not show up (note the presence of the `/` at the end)
     - `curl http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/`
     - <img width="1006" alt="Screen Shot 2021-01-13 at 3 09 43 PM" src="https://user-images.githubusercontent.com/58287848/104522139-27ca2c00-55b3-11eb-84a6-537e3e0b77e0.png">
- A discussion that might be related [https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/459]( https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/459)

**Comment by shermanyin** [comment]
Closing stale issue.
