### ISSUE TITLE
AWS CLI is a requirement for the Manual Terraform Deployment

### ISSUE THREAD

**Issue by jackliu-teradici** [teradici/cloud_deployment_scripts#198]
I'm think the documentation assumes that the user has the relevant CLI already installed but you would hit a barrier without knowing that it's a requirement

https://github.com/teradici/cloud_deployment_scripts/blob/master/docs/aws/README.md#requirements

**Comment by shermanyin** [comment]
Thanks for reporting this.  AWS Terraform deployments doesn't require AWS CLI (just verified), but the AWS quickstart does.  We haven't implemented the auto installation yet (https://github.com/teradici/cloud_deployment_scripts/blob/master/quickstart/aws/aws-quickstart.py#L201) but will do so shortly.
