### ISSUE TITLE
Teradici Download Token

### ISSUE THREAD

**Issue by JafoFett** [teradici/cloud_deployment_scripts#200]
Trying to use the deployment script and I'm fumbling at the download token for teradici...getting a trust error.

--> Downloading PCoIP graphics agent from https://dl.teradici.com/xXZvMRtQ5hFRw6ed/pcoip-agent/raw/names/pcoip-agent-graphics-exe/versions/latest/pcoip-agent-graphics_latest.exe...
Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: Could not establish trust 
relationship for the SSL/TLS secure channel."

Am I doing something wrong here or do I need to grab a new token everytime i want to use the pipeline?

**Comment by JafoFett** [comment]
I think this is a internal issue since our http requests are going out though zscaler and there might be ssl inspection on.

**Comment by shermanyin** [comment]
Hi JafoFett, thanks for your interest in our Terraform configuration. For the same customer account, the token should be the same and you wouldn't need to grab a new token every time.  I tried clicking on the link above with your token and was able to download the file via my browser. You're right, the download might have been prevented by some sort of network setting in your environment.

If you have no control over your network settings, a workaround could be just to download the file another way (e.g. through your browser), save the file somewhere accessible by your workstations in the cloud (e.g. a bucket, file server, etc) and update the script to point to the new URL. It's a one-liner change in each provisioning script. (e.g. https://github.com/teradici/cloud_deployment_scripts/blob/master/modules/gcp/win-gfx/win-gfx-provisioning.ps1.tmpl#L187 )

**Comment by JafoFett** [comment]
Thanks for the reply, and yes it was zscaler and ssl inspection that was causing the issue, simple fix was to have the workstation on the domain and it's all working...
For the same script file (win-gfx-provisioning.ps1) would it be possible to set the nvidia driver to the 'latest' rather that hard coding the version?

**Comment by JafoFett** [comment]
And to this, do you have a powershell script for updating the teradici agent in silent mode? Curious as we deploy the agent out to fleet that users can't update agent cause it's in use...so we need a way to update agent from a powershell script I suppose.

**Comment by shermanyin** [comment]
Regarding the nvidia driver, we pin the version to a specific, known working version (we are in the process of updating it this week for the latest agents). However, if you want to use another version, feel free to replace the URL in the script to one of these here for GCP: https://cloud.google.com/compute/docs/gpus/grid-drivers-table, for example.

Please do first check which version has been tested by Teradici for our agent (e.g. for Windows Graphics agent, check here:  https://www.teradici.com/web-help/pcoip_agent/graphics_agent/windows/22.04/admin-guide/requirements/system-requirements/)  

We don't have silent update scripts, but let me check with my team and get back to you on Tuesday.

**Comment by shermanyin** [comment]
Does this help? https://www.teradici.com/web-help/pcoip_agent/graphics_agent/windows/22.04/admin-guide/installing/installing-the-agent/#scripted-installations

**Comment by JafoFett** [comment]
Yeah, that looks like it'll help, thanks.

**Comment by shermanyin** [comment]
FYI the nvidia drivers have been updated for the just released 22.04 CAS Agents. https://github.com/teradici/cloud_deployment_scripts/commit/78944227d98dd6496bf5ce938eac8f278a3a49fd

I'll close this issue for now, feel free to create another issue again if you have other questions.
